### ISSUE TITLE
Fighter Overhaul

### ISSUE THREAD

**Issue by Startome** [EndlessSkyCommunity/endless-sky#48]
Hyratel and I feel that the current system for the use of fighters and drones is unbalanced, and has led to many players abandoning the idea of using them altogether.

When the NPC ships spawn with a full complement, players often find fighters to be very interesting. But when they try to use them, find that they die very quickly in a battle, and that a standard warship would have been a better choice than a fighter.

Also the need to spend money to replace them, where a standard warship never would have died in the first place, is also quite a deterrent.

The need to spend money to replenish them, and the fact they often die before doing any damage in a large battle, essentially rules them out as a combat effective option. A Captured capital ship makes a much better meat shield.

Especially considering that most players customize their ships, including fighters. The loss of a single fighter can take quite some time to replace, and they are often lost far faster than they can be rebuilt.
So we propose adjusting the fighter system to be more appealing to the player, and more practical, without breaking the game’s balance. This being to expand interest, and most importantly, strategies available.

I know this idea has been suggested in the past, however only as a quick request for some kind of solution. Not that I have read, has a concrete proposal been brought forth.

The most important part of our proposal is to add a module that allows carrier ships to gradually, at high energy and heat cost (and perhaps resources, depending on the ease of coding and balance), to regenerate their fighters both during and after battles. This module would take up a substantial amount of space. The outfit space, combined with the energy and heat demands, would provide the player with two options:

Only equip one manufacturing module, greatly reducing the rate at which the carrier could deploy its fighters, while maintaining weapons. Effectively serving a multirole purpose.

Focus on fighters, allowing the carrier to field fighters at a slightly less tedious rate, but requiring it to serve a true support role, as carriers traditionally do.

We believe a balanced starting point with the numbers would be for the module to occupy 50 general outfit space, while consuming 500 energy and generating 650 heat. This seems fairly realistic for a manufacturing facility, and balances the demands on the player. Meaning early game they have to make sacrifices, as they do with all builds. And late game, as more efficient alien generators, shield mods, etc, are unlocked, they can truly optimize their ships to be the most effective.

The manufacturing module could produce 2 mass per second. This would allow current fighter models to be redeployed (after the initial bay occupant is destroyed in battle) after 52-74 seconds, depending on which fighter. (the boxwing would be lowest, but isn’t truly a combat unit, so is not included)
Current drones would be redeployed at 34-59 seconds, depending on the model.

This module would not drastically affect the balance of any one battle, though the slight changes it would cause seem to be more practical, and more appealing to the player. However it would make even bothering to maintain fighters in one’s navy far more appealing.

Now this idea would be much more appealing if it required the least coding modification possible. As such, one idea would be that in the shipyard where one would normally purchase a fighter, there is a second option for each fighter, one that functions like a “Blueprint” of sorts, which the manufacturing module would reproduce. Obviously this would be noticeably higher in cost than that of its single use fighter.

The Manufacturing module would follow the same concept as shield regenerators and hull repair. When a fleet lands, they function to the maximum effect and completely restore the ship. (if a ship has a hull repair module on board, even on an uninhabited planet, when you land it fully restores)

I did receive a suggestion from comnom that the fighter/drone could be cached when destroyed instead of being removed.
The next obstacle is how to handle the replacement crew for the fighter, as the original pilot died when it was destroyed.
The aim would be to have the game AI replace fighters in the order in which they were destroyed, and auto deploy them if the player hasn’t issued a command to land since the previous deploy command.

We also believe, should this module be implemented, that the players would want new fighters and drones to increase the available strategies. This would help to encourage content creators to add additional fighters and fitting modules as well.

**Comment by TheGiraffe3** [comment]
@MCOfficer this too is still in active discussion on the main repository but has not happened here at all. Should it be closed?

**Comment by MCOfficer** [comment]
this entire repo is a remnant from when we had no control over the main org, so everything here is stale. No point in looking into it.

**Comment by TheGiraffe3** [comment]
Good to know.
