### ISSUE TITLE
Achievement Ideas

### ISSUE THREAD

**Issue by Startome** [EndlessSkyCommunity/endless-sky#49]
A fun way to add a little information for first time players would be to add achievements. That said, Endless Sky being an open source and easily modded game, They need to be achievements that are actual landmark actions, not something that can easily be done with modded or cheated content. As such, I am only proposing ideas that are fairly universal, and can’t just be modded in, like having so many funds or ships.

Some of these ideas are mine, some were contributed by others from the ES community Discord:

Of course if this idea finds your support MZ, I fully expect you will pick and choose options, add your own, and change names and descriptions as you see fit, just want to get the idea out there with some starting place.

Ardent Explorer: Visit Every System in the game.⁰
Starting the Fleet: Have 5 ships in your fleet*
Revolutionist: Complete Free Worlds Storyline.⁰ ²
Businessman: Complete Syndicate Storyline (When Available)⁰
Officer: Complete Republic Storyline (When Available)⁰
Secrets of the Eye: Complete the Wanderer Story.⁰
Glory of Three: Complete Coalition and Heliarch Storylines (When Available)⁰
Blast from the Past: Complete the Remnant Storyline⁰ ²
Trifecta: Capture all three Arfecta’s spawned in the main stories.⁰
Heresy: Destroy Michael Zahniser's Author Kestrel¹
Khan: Reach Maximum Combat Rating²
TMBR: Complete the TMBR Tour²
Conquistador: Demand Tribute from all possible systems.⁰ ⁴
Brawler: Defeat all Sestor Enemies at Farpoint²
Hunter: Defeat all Person Ships (Does not include MZ)⁰ ²
Good Luck, Kid: Complete the Tutorial³
Savescum: Have your flagship destroyed²
The Milky Way Express: Complete 250 Rush Delivery jobs⁴
Heavy Hauler: Complete 250 Bulk deliveries³
Bounty Hunter: Complete 250 Bounty Missions⁰
Founder: Complete 50 Colonist Missions⁰
Defender of the Innocent: Complete 250 Escort Missions⁰
Cruise Master: Complete 250 Transport Missions⁰
Told you so…: Die on Day 1 with a Sparrow Start⁵
Good Samaritan: Repair 250 Disabled friendlies³
Papers, Please: Have all licenses⁵
Unstoppable: Absorb a total of 250,000 damage in a single life⁶
You had one job: Fail a job⁴
Traitor: Destroy a ship you were assigned to protect⁶
Old Salt: Play for 5 in-game years³
Chaff in the Wind: Delete a pilot³
Unreliable: Fail 10 Rush Missions³
Cheapskate: Take off from a planet with insufficient crew to pilot your ship.⁰ ³
Wood for Sheep: Complete a single trade with an over 1 Million Credit Profit⁵
A Dragon’s Hoard: Complete a single trade with an over 1 Billion credit profit.⁵

⁰ Startome
¹ KileDennis
² Brick
³ Czartrak
⁴ Disiuze
⁵ Janaszar
⁶ Hadron
*TheMarksman

**Comment by TheGiraffe3** [comment]
The discussion was in the main repository and this has been open for 5 and a half years with nothing. Should it perhaps be closed @MCOfficer?
