### ISSUE TITLE
Fast forward feature slows the game down incredibly

### ISSUE THREAD

**Issue by Felix-Felis** [EndlessSkyCommunity/endless-sky#56]
**Describe the bug**
Whenever I toggle fast forward, the game slows down significantly

**To Reproduce**
1. toggle fast forward

**Expected behavior**
the game speeds up, not slows down

**System (please complete the following information):**
 - OS: Linux Manjaro
 - Game Source: Steam Beta
 - Version: 0.9.13

**Additional context**
No plugins, game is not modified in any way, happened the day I activated the beta to play on 0.9.13

**Comment by gunqqer** [comment]
If you're launching Endless Sky with the -d, --debug flag caps lock will slow the game by 3 instead of speeding up.
`    -d, --debug: turn on debugging features (e.g. Caps Lock slows down instead of speeds up).`

**Comment by MCOfficer** [comment]
Since you're playing on steam, can you check the following:

- Right click on endless sky in your library
- click "properties"
- go to "launch options"
- make sure that line of text is empty, i.e. you have no launch options

**Comment by MCOfficer** [comment]
Oh and you probably meant to file this over at https://github.com/endless-sky/endless-sky... don't let our confusing repo structure confuse you..

**Comment by tehhowch** [comment]
Another option is to rebind the Fast-forward key, e.g. to `/` or `\`, so then it doesn't matter if you're launching the game in debug mode--you can have speed up, super slow, and photo mode (backtick) at once.

**Comment by Felix-Felis** [comment]
> If you're launching Endless Sky with the -d, --debug flag caps lock will slow the game by 3 instead of speeding up.
> ` -d, --debug: turn on debugging features (e.g. Caps Lock slows down instead of speeds up).`

this was it, thanks :)
